// @ts-nocheck

import { AgentManagementPanel } from './AgentManagementPanel';

interface DashboardAgentManagementSectionProps {
	[key: string]: any;
}

export function DashboardAgentManagementSection({
	agentManagementRef,
	agentTemplateStepRef,
	agentModelStepRef,
	agentKnowledgeStepRef,
	agentToolsStepRef,
	agentRuntimeStepRef,
	platformAgents,
	platformAgentsLoading,
	platformAgentsError,
	agentOpsSummary,
	agentReleasePipeline,
	selectedRunAgent,
	selectedRunAgentReadinessState,
	selectedRunAgentReadinessLabel,
	selectedRunAgentModelLabel,
	selectedRunAgentKnowledgeCount,
	selectedRunAgentToolCount,
	agentTemplates,
	selectedTemplateId,
	selectedTemplate,
	publishingTemplateId,
	editingAgentId,
	agentSetupSteps,
	nextAgentSetupStep,
	publishForm,
	platformStatus,
	credentials,
	credentialsLoading,
	credentialById,
	knowledgeBases,
	knowledgeBaseById,
	publishTenant,
	publishAccessMembers,
	publishRoleOptions,
	publishBlocked,
	publishSelectedModelLabel,
	publishAccessScopeSummary,
	publishRuntimeSummary,
	publishReleaseIssues,
	publishedPlatformAgents,
	activePlatformAgents,
	selectedRunAgentId,
	selectedIdentity,
	archivingAgentId,
	bindingAgentModelId,
	bindingAgentKnowledgeId,
	bindingAgentToolsId,
	enablingAgentMemoryId,
	enablingAgentWorkflowId,
	setPublishForm,
	refetchPlatformAgents,
	handleNextAgentSetupStep,
	scrollToAgentRunner,
	handlePrimeAgentWorkflow,
	handleEditAgent,
	scrollToGovernance,
	handleConfigureTemplate,
	handleCancelEdit,
	handlePublishTenantChange,
	handleTogglePublishList,
	handlePublishAgent,
	handleBindDefaultModel,
	handleBindAvailableKnowledge,
	handleBindTemplateTools,
	handlePrimeToolApproval,
	handleEnableAgentMemory,
	handleEnableAgentWorkflow,
	handleArchiveAgent,
	handlePrimePublishedAgent,
	agentAccessAllowed,
	t,
	cn,
}: DashboardAgentManagementSectionProps) {
	return (
		<AgentManagementPanel
			agentManagementRef={agentManagementRef}
			agentTemplateStepRef={agentTemplateStepRef}
			agentModelStepRef={agentModelStepRef}
			agentKnowledgeStepRef={agentKnowledgeStepRef}
			agentToolsStepRef={agentToolsStepRef}
			agentRuntimeStepRef={agentRuntimeStepRef}
			platformAgents={platformAgents}
			platformAgentsLoading={platformAgentsLoading}
			platformAgentsError={platformAgentsError}
			agentOpsSummary={agentOpsSummary}
			agentReleasePipeline={agentReleasePipeline}
			selectedRunAgent={selectedRunAgent}
			selectedRunAgentReadinessState={selectedRunAgentReadinessState}
			selectedRunAgentReadinessLabel={selectedRunAgentReadinessLabel}
			selectedRunAgentModelLabel={selectedRunAgentModelLabel}
			selectedRunAgentKnowledgeCount={selectedRunAgentKnowledgeCount}
			selectedRunAgentToolCount={selectedRunAgentToolCount}
			agentTemplates={agentTemplates}
			selectedTemplateId={selectedTemplateId}
			selectedTemplate={selectedTemplate}
			publishingTemplateId={publishingTemplateId}
			editingAgentId={editingAgentId}
			agentSetupSteps={agentSetupSteps}
			nextAgentSetupStep={nextAgentSetupStep}
			publishForm={publishForm}
			platformStatus={platformStatus}
			credentials={credentials}
			credentialsLoading={credentialsLoading}
			credentialById={credentialById}
			knowledgeBases={knowledgeBases}
			knowledgeBaseById={knowledgeBaseById}
			publishTenant={publishTenant}
			publishAccessMembers={publishAccessMembers}
			publishRoleOptions={publishRoleOptions}
			publishBlocked={publishBlocked}
			publishSelectedModelLabel={publishSelectedModelLabel}
			publishAccessScopeSummary={publishAccessScopeSummary}
			publishRuntimeSummary={publishRuntimeSummary}
			publishReleaseIssues={publishReleaseIssues}
			publishedPlatformAgents={publishedPlatformAgents}
			activePlatformAgents={activePlatformAgents}
			selectedRunAgentId={selectedRunAgentId}
			selectedIdentity={selectedIdentity}
			archivingAgentId={archivingAgentId}
			bindingAgentModelId={bindingAgentModelId}
			bindingAgentKnowledgeId={bindingAgentKnowledgeId}
			bindingAgentToolsId={bindingAgentToolsId}
			enablingAgentMemoryId={enablingAgentMemoryId}
			enablingAgentWorkflowId={enablingAgentWorkflowId}
			setPublishForm={setPublishForm}
			refetchPlatformAgents={refetchPlatformAgents}
			handleNextAgentSetupStep={handleNextAgentSetupStep}
			scrollToAgentRunner={scrollToAgentRunner}
			handlePrimeAgentWorkflow={handlePrimeAgentWorkflow}
			handleEditAgent={handleEditAgent}
			scrollToGovernance={scrollToGovernance}
			handleConfigureTemplate={handleConfigureTemplate}
			handleCancelEdit={handleCancelEdit}
			handlePublishTenantChange={handlePublishTenantChange}
			handleTogglePublishList={handleTogglePublishList}
			handlePublishAgent={handlePublishAgent}
			handleBindDefaultModel={handleBindDefaultModel}
			handleBindAvailableKnowledge={handleBindAvailableKnowledge}
			handleBindTemplateTools={handleBindTemplateTools}
			handlePrimeToolApproval={handlePrimeToolApproval}
			handleEnableAgentMemory={handleEnableAgentMemory}
			handleEnableAgentWorkflow={handleEnableAgentWorkflow}
			handleArchiveAgent={handleArchiveAgent}
			handlePrimePublishedAgent={handlePrimePublishedAgent}
			agentAccessAllowed={agentAccessAllowed}
			t={t}
			cn={cn}
		/>
	);
}
